### ISSUE TITLE
chloroplast genome totally lost

### ISSUE THREAD

**Issue by njaupan** [ruanjue/smartdenovo#24]
Dear Ruanjue, I have used defult paramater for assembling a plant genome, the mitochondrial genome (~400kb)  is assembled partly but the chloroplast genome (150kb) is totally lost, do you have any suggestion like adjust some paramater? 
Best,
panpan

**Comment by ruanjue** [comment]
It depends on the sequencing depth of MT and CP genomes. 

Usually, they are too high, and be fitlered as highly repetitive. To avoid this, set `wtdmo -K 0`, but will be slower.

Otherwise, the depth is too low, please map raw reads to a relative CP genome, and assembly the mapped reads indepenently.

Jue

**Comment by njaupan** [comment]
Thank you, i will let you know when it's been done.
